# Generated by Django 4.0.6 on 2022-07-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('sobrenome', models.CharField(max_length=250)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=50)),
                ('link_git', models.URLField(blank=True, max_length=150, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
